abbr rm "rm -i"
abbr cp "cp -i"
abbr mv "mv -i"
abbr mkdir "mkdir -p"
abbr h "history"
abbr which "type -a"
abbr .. "cd .."
abbr ... "cd ../.."
abbr .... "cd ../../.."

abbr ls "eza --header -lg"
abbr k "kubectl"
abbr tf "terraform"
abbr python "python3"
abbr py "python3"
abbr cat "bat"
abbr cd "z"
abbr du "dust"
abbr df "duf"
abbr tree "br"
abbr find "fd"
abbr grep "rg"

abbr tmux "tmux -2"