abbr rm  "rm -i"
abbr cp  "cp -i"
abbr mv  "mv -i"
abbr mkdir  "mkdir -p"
abbr h  "history"
abbr which  "type -a"
abbr ..  "cd .."
abbr ...  "cd ../.."

abbr ls  "exa  --header -lg"
abbr k  "kubectl"
abbr tf "terraform"
abbr python  "python3"
abbr py  "python3"

abbr tmux "tmux -2"